# Generated by Django 5.1.1 on 2024-10-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0002_remove_answer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='current_difficulty',
            field=models.CharField(default='easy', max_length=50),
        ),
    ]
